export const AIRTABLE_GET_REQUESTED = 'AIRTABLE_GET_REQUESTED';
export const AIRTABLE_GET_SUCCEEDED = 'AIRTABLE_GET_SUCCEEDED';
export const AIRTABLE_GET_FAILED = 'AIRTABLE_GET_FAILED';
export const AIRTABLE_GET_DISMISSED = 'AIRTABLE_GET_DISMISSED';
export const POST_CHOICES_REQUESTED = 'POST_CHOICES_REQUESTED';
export const POST_CHOICES_SUCCEEDED = 'POST_CHOICES_SUCCEEDED';
export const POST_CHOICES_FAILED = 'POST_CHOICES_FAILED';
export const POST_CHOICES_DISMISSED = 'POST_CHOICES_DISMISSED';
