export const AIRTABLE_GET_REQUESTED = 'AIRTABLE_GET_REQUESTED';
export const AIRTABLE_GET_SUCCEEDED = 'AIRTABLE_GET_SUCCEEDED';
export const AIRTABLE_GET_FAILED = 'AIRTABLE_GET_FAILED';
export const AIRTABLE_GET_DISMISSED = 'AIRTABLE_GET_DISMISSED';

export const AIRTABLE_POST_REQUESTED = 'AIRTABLE_POST_REQUESTED';
export const AIRTABLE_POST_SUCCEEDED = 'AIRTABLE_POST_SUCCEEDED';
export const AIRTABLE_POST_FAILED = 'AIRTABLE_POST_FAILED';
export const AIRTABLE_POST_DISMISSED = 'AIRTABLE_POST_DISMISSED';

export const ADD_DESSERT = 'ADD_DESSERT';
export const REMOVE_DESSERT = 'REMOVE_DESSERT';

export const SET_NAME = 'SET_NAME';
