export const AIRTABLE_GET_REQUESTED = 'AIRTABLE_GET_REQUESTED';
export const AIRTABLE_GET_SUCCEEDED = 'AIRTABLE_GET_SUCCEEDED';
export const AIRTABLE_GET_FAILED = 'AIRTABLE_GET_FAILED';
export const AIRTABLE_GET_DISMISSED = 'AIRTABLE_GET_DISMISSED';

export const ADD_DESSERT = 'ADD_DESSERT';
export const REMOVE_DESSERT = 'REMOVE_DESSERT';
